### ISSUE TITLE
Not able to login

### ISSUE THREAD

**Issue by avinash1sriram** [devdil/gnooble#25]
The website is not redirecting to any other page after successful login

**Comment by devdil** [comment]
Could you please share the setup credentials so that i can see what's going wrong?

**Comment by avinash1sriram** [comment]
http://139.59.34.29/login/ is the link

please let me know if you want anything further more

Regards
Avinash Sriram

**Comment by devdil** [comment]
@avinash1sriram  thanks for the quick response. Could you share the setup ssh username/password and the login credentials?

**Comment by avinash1sriram** [comment]
Thank you for the fast reply sir

I have successfully fixed my problem and I found some bugs in it.

I will let you know if you are interested to know them.

Regards
Avinash sriram

**Comment by devdil** [comment]
if you have fixed the bugs, you can clone and make a pull request, i shall merge it to my main branch.

**Comment by avinash1sriram** [comment]
Ok sir. Thank you.

It will make that as early as possible.

Regards
Avinash Sriram
